version: '3'

services:
  db:
    container_name: mysql
    build: ./mysql/
    ports:
      - "3306:3306"
    env_file:
      - ./mysql/local.env
    restart: unless-stopped
  api:
    restart: unless-stopped
    container_name: fast_api
    build: 
      context: .
      dockerfile: app.Dockerfile
    ports:
      - 8000:80
    env_file:
      - ./app/.env
    depends_on:
      - db
    
